services:
  map-editor-demo:
    image: ${REGISTRY}/${IMAGE_NAME}@${SHA}
    container_name: map-editor-demo
    network_mode: "host"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.map-editor-demo.rule=Host(`map-editor-demo.xzm920.dev`)"
      - "traefik.http.routers.map-editor-demo.entrypoints=websecure"
      - "traefik.http.routers.map-editor-demo.service=map-editor-demo-service"
      - "traefik.http.services.map-editor-demo-service.loadbalancer.server.url=http://127.0.0.1:8000"
    ports:
      - "8000:8000"
