export const EVENT = {
  beforeModelChange: 'beforeModelChange',
  add: 'add',
  remove: 'remove',
  update: 'update',
  sortItem: 'sortItem',
  toggleMaskPlayer: 'toggleMaskPlayer',
  history: 'history',
  zoom: 'zoom',
  viewportTransform: 'viewportTransform',
  viewportResize: 'viewportResize',
  toggleMask: 'toggleMask',
  toggleEffect: 'toggleEffect',
  toggleAlignTile: 'toggleAlignTile',
  contextMenu: 'contextMenu',
  toolChange: 'toolChange',
  selectionChange: 'selectionChange',
  selectionMove: 'selectionMove',
};
